### ISSUE TITLE
Could you please tell me where did you refer the codes in the agent_utils.py file? plz!

### ISSUE THREAD

**Issue by doulemint** [WilliamRusdyputra/RL-Agents#1]
Could you please tell me where did you get the codes in the agent_utils.py file? plz!

**Comment by WilliamRusdyputra** [comment]
I wrote it myself, but following some rl tutorials (mainly pytorch & tensorflow official website and medium posts) and repos in the internet (kinda mix and match). It has been a year, so I forgot which website/repo did I refer to, sorry :(

**Comment by williamrusdyputra** [comment]
> Could you please tell me where did you get the codes in the agent_utils.py file? plz!

I wrote it myself, but following some rl tutorials (mainly pytorch & tensorflow official website and medium posts) and repos in the internet (kinda mix and match). It has been a year, so I forgot which website/repo did I refer to, sorry :(

**Comment by doulemint** [comment]
ok, gotcha, thank you!

**Comment by doulemint** [comment]
nice work, btw
